/home/eliasd/lensing/pyrofit-lensing-analysis/experiments/swyft_unet/scripts
Loading existing store.
Store has 1011 simulations.
Image has L = 40.
Training ../data/mre/mre_real_m_1_nsub_1_nsim_1000_sigma_0.0_nmc_1.pt!
Traceback (most recent call last):
  File "/home/eliasd/lensing/pyrofit-lensing-analysis/experiments/swyft_unet/scripts/train.py", line 103, in <module>
    run()
  File "/home/eliasd/.pyenv/versions/lens-3.9.7/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/eliasd/.pyenv/versions/lens-3.9.7/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/eliasd/.pyenv/versions/lens-3.9.7/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/eliasd/.pyenv/versions/lens-3.9.7/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/eliasd/lensing/pyrofit-lensing-analysis/experiments/swyft_unet/scripts/train.py", line 79, in run
    network = get_custom_marginal_classifier(
TypeError: get_custom_marginal_classifier() missing 1 required positional argument: 'parameter_transform'
